name: main

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: pip install poetry
        run: |
          pip install poetry

      - name: flake8-install
        run: |
          pip install flake8

      - name: flake8-run
        run: |
          poetry run flake8 page_analyzer

      - name: psycopg2-binary
        run: |
          pip install psycopg2-binary
  
